clears_per_week = ["Normal", "Heroic"]
mythic_kills = [3, 4, 5, 6, 7, 7, 7, 8]
mythic_first_slot = "Gloves"
num_samples = 100000
num_extra_vault_items = 3

[trading_rule]
target = "MostSetCompletionsLeastPieces"

[members]
Mango = "Monk"
Schlimm = "Druid"
Milksupply = "Druid"
Prucem = "Monk"
Sethera = "Paladin"
Nikita = "Paladin"
Cleoboltra = "Priest"
Darlays = "DemonHunter"
Jugy = "DemonHunter"
Babs = "Druid"
Celinamuna = "Rogue"
Koji = "Rogue"
Shamlessness = "Shaman"
Deswind = "Warrior"
Seaborg = "Warrior"
Zarantai = "Druid"
Zhot = "Druid"
Dz = "Hunter"
Ogle = "Hunter"
Ugmo = "Hunter"
Jonnycakes = "Mage"
Draddog = "Mage"
Morgrom = "Priest"
Morrgaux = "Priest"
Jake = "Warlock"
Ed = "Warlock"
