clears_per_week = ["Heroic", "Normal"]
mythic_kills = [3, 4, 5, 6, 7, 7, 7, 8]
mythic_first_slot = "Gloves"
num_samples = 100000
num_extra_vault_items = 3

[trading_rule]
target = "MostSetCompletionsLeastPieces"

[members]
Manghoe = "Monk"
Schlimmy = "Druid"
Milksupply = "Druid"
Prucem = "Monk"
Setth = "Paladin"
Cleoboltra = "Priest"
Nikitaqt = "Shaman"
Darlayys = "DemonHunter"
Jugy = "DemonHunter"
Babiyama = "Druid"
Celinamuna = "Rogue"
Kartra = "Rogue"
Tenpercent = "Shaman"
Deswind = "Warrior"
Seaborg = "Warrior"
Zarantai = "Druid"
Zhot = "Druid"
Dzlirium = "Hunter"
Oglethorny = "Hunter"
Ugmoh = "Hunter"
Spyrosocold = "Mage"
Draddog = "Mage"
Morghosts = "Priest"
Ottalauss = "Shaman"
Edennil = "Warlock"
Jakerator = "Warlock"
Impoopdollar = "Warlock"
